name: polka
base: core22
summary: Polka Snap App
description: A Snap package for the Polka app.
adopt-info: polka-app

grade: stable
confinement: strict

apps:
  polka:
    command: bin/polka

parts:
  polka-app:
    plugin: dump
    source: https://github.com/erik78se/polka.git
    source-tag: v0.9.44
    override-pull: |
      craftctl default
      craftctl set version="$(git describe --tags --abbrev=10)-$(git rev-parse --short HEAD)"
